server:
  port: 80

logging:
  level:
    adou.community.mapper:
     debug

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  type-aliases-package: adou.community.model
  configuration:
    map-underscore-to-camel-case: true
  #config-location: classpath:/mybatis/mybatis-config.xml