server:
  port: 80

logging:
  level:
    root:
      info
    adou.community.mapper:
      debug

  file:
    name:
      logs/community.log
    max-size: 100MB
    max-history: 15


mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  type-aliases-package: adou.community.model
  configuration:
    map-underscore-to-camel-case: true
  #config-location: classpath:/mybatis/mybatis-config.xml